import 'package:flutter/material.dart';

const sizedBox = SizedBox();
const sizedBoxW2 = SizedBox(width: 2);
const sizedBoxW4 = SizedBox(width: 4);
const sizedBoxW5 = SizedBox(width: 5);
const sizedBoxW6 = SizedBox(width: 6);
const sizedBoxW8 = SizedBox(width: 8);
const sizedBoxW10 = SizedBox(width: 10);
const sizedBoxW12 = SizedBox(width: 12);
const sizedBoxW16 = SizedBox(width: 16);
const sizedBoxW20 = SizedBox(width: 20);
const sizedBoxW30 = SizedBox(width: 30);
const sizedBoxH2 = SizedBox(height: 2);
const sizedBoxH4 = SizedBox(height: 4);
const sizedBoxH5 = SizedBox(height: 5);
const sizedBoxH6 = SizedBox(height: 6);
const sizedBoxH8 = SizedBox(height: 8);
const sizedBoxH10 = SizedBox(height: 10);
const sizedBoxH12 = SizedBox(height: 12);
const sizedBoxH16 = SizedBox(height: 16);
const sizedBoxH20 = SizedBox(height: 20);
const sizedBoxH30 = SizedBox(height: 30);